//
//  UrlConstants.h
//  edum
//
//  Created by Kevin Chan on 30/12/2019.
//  Copyright © 2019 MD Chen. All rights reserved.
//

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

@interface UrlConstants : NSObject

FOUNDATION_EXPORT NSString *const BASE_URL;
FOUNDATION_EXPORT NSString *const BASE_PLATFORM;
FOUNDATION_EXPORT NSString *const BASE_VERSION;

FOUNDATION_EXPORT NSString *const REQUEST_SYSTEM_LOGIN;
FOUNDATION_EXPORT NSString *const REQUEST_SYSTEM_LOGOUT;

FOUNDATION_EXPORT NSString *const REQUEST_USER_SENDCODE;
FOUNDATION_EXPORT NSString *const REQUEST_USER_LOGINPHONECODE;

FOUNDATION_EXPORT NSString *const REQUEST_LANDING_LIST;

FOUNDATION_EXPORT NSString *const REQUEST_LANDING_COURSE;
FOUNDATION_EXPORT NSString *const REQUEST_LANDING_TEACHER;
FOUNDATION_EXPORT NSString *const REQUEST_SEGMENT_COURSE;
FOUNDATION_EXPORT NSString *const REQUEST_SEGMENT_TEACHER;

FOUNDATION_EXPORT NSString *const REQUEST_TEACHER;
FOUNDATION_EXPORT NSString *const REQUEST_COURSE;

FOUNDATION_EXPORT NSString *const REQUEST_COURSE_SEARCH;

FOUNDATION_EXPORT NSString *const REQUEST_LANDING_NEWS;
FOUNDATION_EXPORT NSString *const REQUEST_COURSE_DETAIL;

FOUNDATION_EXPORT NSString *const REQUEST_CALENDAR_LIST;
FOUNDATION_EXPORT NSString *const REQUEST_CALENDAR_WEEK;
FOUNDATION_EXPORT NSString *const REQUEST_CALENDAR_DETAIL;
FOUNDATION_EXPORT NSString *const REQUEST_CALENDAR_ADD;
FOUNDATION_EXPORT NSString *const REQUEST_CALENDAR_COURSE;
FOUNDATION_EXPORT NSString *const REQUEST_TEACHER_CALENDAR;

FOUNDATION_EXPORT NSString *const REQUEST_USER_NOTIFICATION;
FOUNDATION_EXPORT NSString *const REQUEST_ALL_COURESE;

FOUNDATION_EXPORT NSString *const REQUEST_PROFILE;
FOUNDATION_EXPORT NSString *const REQUEST_PROFILE_LIST;


@end

NS_ASSUME_NONNULL_END
